import 'package:flutter/material.dart';

class NetworkConstant{

  static const String BASE_URL='https://myfancy11.com';//'https://bigfan247.com';
  static const String VERIFY_MOBILE_NUMBER_URL='/app/phone_valided';
  static const String REFER_VALIDATION_ROUTE_URL='/app/refer_valided';
  static const String LOGIN_ROUTE_URL='/app/login';
  static const String REGISTER_ROUTE_URL='/app/register';
  static const String ACCOUNT_UPDATE_URL='/app/account_update';
  static const String CUSTOMER_DATE_ROUTE_URL='/app/splash';
  static const String GET_AWATAR_LIST_ROUTE_URL='/app/avatar';
  static const String GET_MATCHES='/app/match';
  static const String GET_CONTEST='/app/contest';
  static const String GET_WINNING_INFO='/app/winning_info';
  static const String GET_LEADERBOARD_URL='/app/leaderboard';
  static const String Get_Squad='/app/squad';
  static const String Save_Team_URL='/app/save_team';
  static const String Wallet_Url='/app/wallet';
  static const String Join_Contest='/app/join_contest';
  static const String Notification_url='/app/notification';
  static const String MyMatchList_Url='/app/my_match';
  static const String Get_transaction_history_url='/app/tracker';
  static const String Match_by_id='/app/match_by_id';
  static const String My_Contest='/app/my_contest';
  static const String My_paid_Team='/app/my_paid_team';
  static const String player='/app/player';
  static const String recharge='/app/recharge';
  static const String getQuizCategory='/app/quiz_category';
  static const String getQuizById='/app/quiz_match_by_id';
  static const String getQuizByCategory='/app/quiz_list';
  static const String quizDetails='/app/quiz_by_id';
  static const String buyQuiz='/app/quiz_join';
  static const String getMyPlayers='/app/my_player';
  static const String quizByMatchId='/app/quiz_match_by_id';
  static const String getMyQuizList='/app/quiz_my_list';
 static const String sellQuiz='/app/quiz_sale';
 static const String refferData='/app/my_refer';
 static const String checkEkyc='/app/check_kyc';
 static const String requestEkyc='/app/kyc_request';
 static const String myPaidTeam='/app/my_paid_team';
 static const String cloneTeam='/app/clone';
 static const String upgrade_account='/app/refer_upgrade';
 static const String set_reminder='/app/set_reminder';
 static const String applyPromoCode='/app/promo';
 static const String validatePromoCode='/app/promo_valided';
 static const String requestForWithdrawal='/app/payment_request';
 static const String winner_api='/app/winner';
 static const String myTeamApi='/app/my_team';
static const String getUpi='/app/getupi';
static const String check_status='/app/check_status';
  //parames.

  static const String PHONE_PARAMS='phone';
  static const String USER_TOKEN='user_token';
  static const String Package_Name='package_name';
  static const String Device_Name='device_name';
  static const String One_Signal='one_signal';
  static const String Login_Method='method';
  static const String Login_Id='login_id';
  static const String Reffer_By='referby';
  static const String Email='email';
  static const String Name='name';
  static const String Profile='profile';
  static const String Status='status';
  static const String MatchId='match_id';
  static const String ContestId='contest_id';
  static const String Designationid='designationid';
  static const String MyTeam='my_team';
  static const String MyTeamId='my_team_id';
  static const String List='list';
  static const String CaptainId='captain_id';
  static const String Vice_Captain_Id='vice_captain_id';
  static const String PlayerId='PlayerId';
  static const String playerid='playerid';
  static const String amount='amount';
  static const String mode='mode';
  static const String transaction_details='transection_details';
  static const String status='status';

}