// {
//     "status": 200,
//     "message": "Contest Found",
//     "data": [
//         {
//             "id": "1",
//             "name": "Mega Contest",
//             "status": "1",
//             "data": [
//                 {
//                     "contest_id": "1",
//                     "contest_name": "Practice Contest",
//                     "contest_tag": "Get ready for mega winnings!",
//                     "winners": "25",
//                     "prize_pool": "0",
//                     "total_team": "50",
//                     "join_team": "0",
//                     "entry": "0",
//                     "contest_description": "The actual prize money may be different than the prize money mentioned above if there is a tie for any of the winning positions. Check FAQs for further details . As per government regulations, a tax of 31.2% will be deducted.",
//                     "contest_note1": "Winnings are confirmed even if this contest doesn't fill up",
//                     "contest_note2": "In this multi-entry contest, join with up to 6 teams",
//                     "winning_note": "Winning",
//                     "match_id": "1",
//                     "type": "1",
//                     "first_prize": "100000",
//                     "win_percent": "40",
//                     "team_upto": "10",
//                     "contest_status": "1",
//                     "contest_paid": "running",
//                     "bonus_entry": "5",
//                     "spend_earn": "10-1",
//                     "offer": {
//                         "offer_id": "1",
//                         "thumb": "https://ui-avatars.com/api/?background=random&name=John+Doe",
//                         "contest_id": "1",
//                         "comment": "May Be in Feature modify this Offer like Add New Field",
//                         "status": "1",
//                         "title": "Rank 1-3 Win Iphone14"
//                     }
//                 },
//                 {
//                     "contest_id": "2",
//                     "contest_name": "Triple Thread",
//                     "contest_tag": "Winner",
//                     "winners": "1",
//                     "prize_pool": "44",
//                     "total_team": "3",
//                     "join_team": "0",
//                     "entry": "17",
//                     "contest_description": "Enjoy winning",
//                     "contest_note1": "0",
//                     "contest_note2": "0",
//                     "winning_note": "",
//                     "match_id": "1",
//                     "type": "1",
//                     "first_prize": "0",
//                     "win_percent": "0",
//                     "team_upto": "0",
//                     "contest_status": "1",
//                     "contest_paid": "running",
//                     "bonus_entry": "5",
//                     "spend_earn": "10-1",
//                     "offer": "null"
//                 }
//             ]
//         },
//         {
//             "id": "2",
//             "name": "Multiplayer Contest",
//             "status": "1",
//             "data": [
//                 {
//                     "contest_id": "3",
//                     "contest_name": "Head to Head",
//                     "contest_tag": "Winner",
//                     "winners": "1",
//                     "prize_pool": "15",
//                     "total_team": "2",
//                     "join_team": "0",
//                     "entry": "10",
//                     "contest_description": "Enjoy winning",
//                     "contest_note1": "0",
//                     "contest_note2": "0",
//                     "winning_note": "",
//                     "match_id": "1",
//                     "type": "2",
//                     "first_prize": "0",
//                     "win_percent": "0",
//                     "team_upto": "0",
//                     "contest_status": "1",
//                     "contest_paid": "running",
//                     "bonus_entry": "5",
//                     "spend_earn": "10-1",
//                     "offer": "null"
//                 },
//                 {
//                     "contest_id": "4",
//                     "contest_name": "Practice Contest",
//                     "contest_tag": "Get ready for mega winnings!",
//                     "winners": "25",
//                     "prize_pool": "0",
//                     "total_team": "50",
//                     "join_team": "0",
//                     "entry": "0",
//                     "contest_description": "The actual prize money may be different than the prize money mentioned above if there is a tie for any of the winning positions. Check FAQs for further details . As per government regulations, a tax of 31.2% will be deducted.",
//                     "contest_note1": "Winnings are confirmed even if this contest doesn't fill up",
//                     "contest_note2": "In this multi-entry contest, join with up to 6 teams",
//                     "winning_note": "Winning",
//                     "match_id": "1",
//                     "type": "2",
//                     "first_prize": "0",
//                     "win_percent": "0",
//                     "team_upto": "0",
//                     "contest_status": "1",
//                     "contest_paid": "running",
//                     "bonus_entry": "5",
//                     "spend_earn": "10-1",
//                     "offer": "null"
//                 }
//             ]
//         },
//         {
//             "id": "3",
//             "name": "Only for Begginers",
//             "status": "1",
//             "data": [
//                 {
//                     "contest_id": "5",
//                     "contest_name": "Triple Thread",
//                     "contest_tag": "Winner",
//                     "winners": "1",
//                     "prize_pool": "44",
//                     "total_team": "3",
//                     "join_team": "0",
//                     "entry": "17",
//                     "contest_description": "Enjoy winning",
//                     "contest_note1": "0",
//                     "contest_note2": "0",
//                     "winning_note": "",
//                     "match_id": "1",
//                     "type": "3",
//                     "first_prize": "0",
//                     "win_percent": "0",
//                     "team_upto": "0",
//                     "contest_status": "1",
//                     "contest_paid": "running",
//                     "bonus_entry": "5",
//                     "spend_earn": "10-1",
//                     "offer": "null"
//                 },
//                 {
//                     "contest_id": "6",
//                     "contest_name": "Head to Head",
//                     "contest_tag": "Winner",
//                     "winners": "1",
//                     "prize_pool": "15",
//                     "total_team": "2",
//                     "join_team": "0",
//                     "entry": "10",
//                     "contest_description": "Enjoy winning",
//                     "contest_note1": "0",
//                     "contest_note2": "0",
//                     "winning_note": "",
//                     "match_id": "1",
//                     "type": "3",
//                     "first_prize": "0",
//                     "win_percent": "0",
//                     "team_upto": "0",
//                     "contest_status": "1",
//                     "contest_paid": "running",
//                     "bonus_entry": "5",
//                     "spend_earn": "10-1",
//                     "offer": "null"
//                 }
//             ]
//         }
//     ]
// }